apiVersion: v1
kind: PersistentVolume
metadata:
  name: mysql0-pv
spec:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 2Gi
  hostPath:
    path: /datafiles/database/mysql
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: mysql1-pv
spec:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 2Gi
  hostPath:
    path: /datafiles/database/mysql
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: mysql2-pv
spec:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 2Gi
  hostPath:
    path: /datafiles/database/mysql
